networks:
    default: moonriver
    moonriver:
        gas_limit: max
        gas_price: 1_000_000_000

compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - zeppelin=./node_modules/@openzeppelin/contracts