networks:
    default: development
    moonriver:
        gas_limit: 15_000_000
        gas_price: 1_000_000_000

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0

compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 10
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0"

reports:
  exclude_contracts:
    - Clones
    - vAccounts_mock
    - vKSM_mock
    - AUX_mock
    - TransparentUpgradeableProxy
    - ProxyAdmin
    - SafeCast
    - SafeMath
    - Address