compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - zeppelin=./node_modules/@openzeppelin/contracts