name: Linters

on:
  push:
    branches:
    - main
    - develop
  pull_request:

jobs:
  lint-test:
    name: Solidity linters
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup node.js version
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache yarn cache
      id: cache-yarn-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: node_modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install modules
      run: yarn
      if: |
        steps.cache-yarn-cache.outputs.cache-hit != 'true' ||
        steps.cache-node-modules.outputs.cache-hit != 'true'
    
    - name: Run Solidity linters
      run: yarn lint:sol:solhint
